
Topics
~~~~~~~~~~~~~~~~~~~
	All commands (alphabetical)
		https://docs.snowflake.com/en/sql-reference/sql-all
	  

Overview
SQL data types reference
   Summary
   Numeric
   String & binary
      Binary input and output formats
      Working with binary values
   Logical
   Date & time
      Input and output formats
      Working with date and time values
   Semi-structured
   Structured
   Geospatial
   Vector
   Unsupported
   Conversion

SQL command reference
	Query syntax
		SELECT
		WITH
		TOP <n>
		INTO
		FROM
		AT
		BEFORE
		CHANGES
		CONNECT BY
		JOIN
		ASOF JOIN
		LATERAL
		MATCH_RECOGNIZE
		PIVOT
		UNPIVOT
		VALUES
		SAMPLE
		TABLESAMPLE
		WHERE
		GROUP BY
		GROUP BY CUBE
		GROUP BY GROUPING SETS
		GROUP BY ROLLUP
		HAVING
		QUALIFY
		ORDER BY
		LIMIT
		FETCH
		FOR UPDATE
	Query operators
		Arithmetic
		Comparison
		Logical
		Set operators
		Subquery
	General DDL
		ALTER
		COMMENT
		CREATE
		CREATE OR ALTER
		DESCRIBE
		DROP
		UNDROP
		SHOW
		USE
	General DML
		INSERT
		MERGE
		UPDATE
		DELETE
		TRUNCATE
	All commands (alphabetical)
		https://docs.snowflake.com/en/sql-reference/sql-all
	  
	Accounts
		Organization
			ALTER ACCOUNT
			CREATE ACCOUNT
			DROP ACCOUNT
			SHOW ACCOUNTS
			SHOW GLOBAL ACCOUNTS
			UNDROP ACCOUNT
		Organization account
			ALTER ORGANIZATION ACCOUNT
			CREATE ORGANIZATION ACCOUNT
			SHOW ORGANIZATION ACCOUNTS
		Managed accounts
			CREATE MANAGED ACCOUNT
			DROP MANAGED ACCOUNT
			SHOW MANAGED ACCOUNTS
		Account parameters & functions
			ALTER ACCOUNT
			SHOW FUNCTIONS
	Users, roles, & privileges
		User management
			CREATE USER
			ALTER USER
			DROP USER
			DESCRIBE USER
			SHOW USERS
		Database role management
			CREATE DATABASE ROLE
			ALTER DATABASE ROLE
			DROP DATABASE ROLE
			SHOW DATABASE ROLES
			GRANT DATABASE ROLE
			REVOKE DATABASE ROLE
			GRANT DATABASE ROLE ... TO SHARE
			REVOKE DATABASE ROLE ... FROM SHARE
		Account-level role management
			CREATE ROLE
			ALTER ROLE
			DROP ROLE
			SHOW ROLES
			GRANT ROLE
			REVOKE ROLE
			USE ROLE
			USE SECONDARY ROLES
		Privilege management
			GRANT <privilege> ... TO APPLICATION
			REVOKE <privilege> ... FROM APPLICATION
			GRANT <privilege> ... TO APPLICATION ROLE
			REVOKE <privilege> ... FROM APPLICATION ROLE
			GRANT <privileges> ... TO ROLE
			REVOKE <privileges> ... FROM ROLE
			GRANT <privilege> ... TO SHARE
			REVOKE <privilege> ... FROM SHARE
			GRANT OWNERSHIP
			SHOW GRANTS		 
	Integrations
		General
			CREATE INTEGRATION
			ALTER INTEGRATION
			SHOW INTEGRATIONS
			DESCRIBE INTEGRATION
			DROP INTEGRATION
		API
			CREATE API INTEGRATION
			ALTER API INTEGRATION
		Catalog
			CREATE CATALOG INTEGRATION
				AWS Glue
				Object storage
				Snowflake Open Catalog integration
				Apache Iceberg™ REST
			ALTER CATALOG INTEGRATION
			DROP CATALOG INTEGRATION
			SHOW CATALOG INTEGRATIONS
			DESCRIBE CATALOG INTEGRATION
		External access
			CREATE EXTERNAL ACCESS INTEGRATION
			ALTER EXTERNAL ACCESS INTEGRATION
		Notification
			CREATE NOTIFICATION INTEGRATION
				Azure Event Grid topics (inbound)
				Google Pub/Sub topics (inbound)
				Amazon SNS topics (outbound)
				Azure Event Grid topics (outbound)
				Google Pub/Sub topics (outbound)
				Email
				Webhooks			
			ALTER NOTIFICATION INTEGRATION
				Azure Event Grid topics (inbound)
				Google Pub/Sub topics (inbound)
				Amazon SNS topics (outbound)
				Azure Event Grid topics (outbound)
				Google Pub/Sub topics (outbound)
				Email
				Webhooks			
		Security
				CREATE SECURITY INTEGRATION
					AWS IAM
					External API authentication
					External OAuth
					Snowflake OAuth
					SAML2
					SCIM				
				ALTER SECURITY INTEGRATION
					AWS IAM
					External API authentication
					External OAuth
					Snowflake OAuth
					SAML2
					SCIM							
				SHOW DELEGATED AUTHORIZATIONS
		Storage
			CREATE STORAGE INTEGRATION
			ALTER STORAGE INTEGRATION
	Replication & failover
		SHOW REPLICATION ACCOUNTS
		SHOW REPLICATION DATABASES
		SHOW REGIONS	
		Replication
			CREATE REPLICATION GROUP
			ALTER REPLICATION GROUP
			DROP REPLICATION GROUP
			SHOW REPLICATION GROUPS
			SHOW DATABASES IN REPLICATION GROUP
			SHOW SHARES IN REPLICATION GROUP
		Failover/failback
			CREATE FAILOVER GROUP
			ALTER FAILOVER GROUP
			DROP FAILOVER GROUP
			SHOW FAILOVER GROUPS
			SHOW DATABASES IN FAILOVER GROUP
			SHOW SHARES IN FAILOVER GROUP
		Client Redirect
			CREATE CONNECTION
			ALTER CONNECTION
			DROP CONNECTION
			SHOW CONNECTIONS	
	Sessions
		Parameters
			ALTER SESSION
			SHOW PARAMETERS
		Context
			USE ROLE
			USE SECONDARY ROLES
			USE WAREHOUSE
			USE DATABASE
			USE SCHEMA
		Variables
			SET
			UNSET
			SHOW VARIABLES
		Queries
			EXPLAIN
			DESCRIBE RESULT	
	Transactions
		BEGIN
		COMMIT
		DESCRIBE TRANSACTION
		ROLLBACK
		SHOW LOCKS
		SHOW TRANSACTIONS	
	Virtual warehouses & resource monitors
		Virtual warehouses
			CREATE WAREHOUSE
			ALTER WAREHOUSE
			DESCRIBE WAREHOUSE
			DROP WAREHOUSE
			USE WAREHOUSE
			SHOW WAREHOUSES
		Resource monitors
			CREATE RESOURCE MONITOR
			ALTER RESOURCE MONITOR
			DROP RESOURCE MONITOR
			SHOW RESOURCE MONITORS	
	Databases, schemas, & shares
		Database
			CREATE DATABASE
			ALTER DATABASE
			DESCRIBE DATABASE
			DROP DATABASE
			UNDROP DATABASE
			USE DATABASE
			SHOW DATABASES
		Schema
			ALTER SCHEMA
			DESCRIBE SCHEMA
			CREATE SCHEMA
			DROP SCHEMA
			UNDROP SCHEMA
			USE SCHEMA
			SHOW SCHEMAS
		Share
			ALTER SHARE
			CREATE SHARE
			DROP SHARE
			SHOW SHARES
			DESCRIBE SHARE	
	Tables, views, & sequences
		SHOW OBJECTS
			Table
				CREATE TABLE
					CREATE TABLE ... CONSTRAINT
				ALTER TABLE
					ALTER TABLE ... ALTER COLUMN
				DROP TABLE
				UNDROP TABLE
				SHOW TABLES
				SHOW COLUMNS
				SHOW PRIMARY KEYS
				DESCRIBE TABLE
				DESCRIBE SEARCH OPTIMIZATION
				TRUNCATE TABLE
			Dynamic table
				CREATE DYNAMIC TABLE
				ALTER DYNAMIC TABLE
				DESCRIBE DYNAMIC TABLE
				DROP DYNAMIC TABLE
				UNDROP DYNAMIC TABLE
				SHOW DYNAMIC TABLES
			Event table
				CREATE EVENT TABLE
				ALTER TABLE (Event Table)
				SHOW EVENT TABLES
				DESCRIBE EVENT TABLE
			External table
				CREATE EXTERNAL TABLE
				ALTER EXTERNAL TABLE
				DROP EXTERNAL TABLE
				SHOW EXTERNAL TABLES
				DESCRIBE EXTERNAL TABLE
			Hybrid table
				CREATE HYBRID TABLE
				CREATE INDEX
				DROP INDEX
				SHOW HYBRID TABLES
				SHOW INDEXES
			Apache Iceberg™ table
				CREATE ICEBERG TABLE
					Snowflake catalog
					AWS Glue catalog
					Iceberg files
					Delta
					Iceberg REST
				ALTER ICEBERG TABLE
					ALTER ICEBERG TABLE ... REFRESH
					ALTER ICEBERG TABLE ... CONVERT TO MANAGED
					ALTER ICEBERG TABLE ... ALTER COLUMN ... SET DATA TYPE
				DROP ICEBERG TABLE
				UNDROP ICEBERG TABLE
				SHOW ICEBERG TABLES
				DESCRIBE ICEBERG TABLE
			View
				CREATE VIEW
				ALTER VIEW
				DROP VIEW
				SHOW VIEWS
				DESCRIBE VIEW
			Materialized view
				CREATE MATERIALIZED VIEW
				ALTER MATERIALIZED VIEW
				DROP MATERIALIZED VIEW
				SHOW MATERIALIZED VIEWS
				DESCRIBE MATERIALIZED VIEW
				TRUNCATE MATERIALIZED VIEW
			Sequence
				CREATE SEQUENCE
				ALTER SEQUENCE
				DROP SEQUENCE
				SHOW SEQUENCES
				DESCRIBE SEQUENCE
	Functions, procedures, & scripting
		User-defined function
			ALTER FUNCTION
			CREATE FUNCTION
			DROP FUNCTION
			DESCRIBE FUNCTION
			SHOW USER FUNCTIONS
		Data metric function
			CREATE DATA METRIC FUNCTION
			ALTER FUNCTION (DMF)
			DESCRIBE FUNCTION (DMF)
			DROP FUNCTION (DMF)
			SHOW DATA METRIC FUNCTIONS
		Service function
			CREATE FUNCTION (Service)
			ALTER FUNCTION (Service)
			DESCRIBE FUNCTION (Service)
			DROP FUNCTION (Service)
		External function
			CREATE EXTERNAL FUNCTION
			ALTER FUNCTION
			SHOW EXTERNAL FUNCTIONS
			DROP FUNCTION
			DESCRIBE FUNCTION
		Stored procedure
			CALL
			CALL WITH
			CREATE PROCEDURE
			ALTER PROCEDURE
			DROP PROCEDURE
			SHOW PROCEDURES
			DESCRIBE PROCEDURE
		Scripting
			EXECUTE IMMEDIATE
			EXECUTE IMMEDIATE FROM
		Git repository
			CREATE GIT REPOSITORY
			ALTER GIT REPOSITORY
			DROP GIT REPOSITORY
			DESCRIBE GIT REPOSITORY
			SHOW GIT REPOSITORIES
			SHOW GIT BRANCHES
			SHOW GIT TAGS
	Streams & tasks
		Stream
			CREATE STREAM
			ALTER STREAM
			DESCRIBE STREAM
			DROP STREAM
			SHOW STREAMS
		Task
			CREATE TASK
			DESCRIBE TASK
			ALTER TASK
			DROP TASK
			EXECUTE TASK
			SHOW TASKS
	Classes & instances
		SHOW CLASSES
	Machine learning models
		Models
			CREATE MODEL
			ALTER MODEL
			DROP MODEL
			SHOW MODELS
		Versions
			ALTER MODEL ... ADD VERSION
			ALTER MODEL ... DROP VERSION
			ALTER MODEL ... MODIFY VERSION
			SHOW VERSIONS IN MODEL
		Functions
			SHOW FUNCTIONS IN MODEL
	Cortex Search Service
		ALTER CORTEX SEARCH SERVICE
		CREATE CORTEX SEARCH SERVICE
		DESCRIBE CORTEX SEARCH SERVICE
		DROP CORTEX SEARCH SERVICE
		SHOW CORTEX SEARCH SERVICE
	Listings
		ALTER LISTING
		CREATE LISTING
		DESCRIBE AVAILABLE LISTING
		DESCRIBE LISTING
		DROP LISTING
		SHOW AVAILABLE LISTINGS
		SHOW LISTINGS
	Security
		Authentication policy
			CREATE AUTHENTICATION POLICY
			ALTER AUTHENTICATION POLICY
			DROP AUTHENTICATION POLICY
			SHOW AUTHENTICATION POLICIES
			DESCRIBE AUTHENTICATION POLICY
		Network policy
			CREATE NETWORK POLICY
			ALTER NETWORK POLICY
			DROP NETWORK POLICY
			SHOW NETWORK POLICIES
			DESCRIBE NETWORK POLICY
		Network rule
			CREATE NETWORK RULE
			ALTER NETWORK RULE
			DROP NETWORK RULE
			SHOW NETWORK RULES
			DESCRIBE NETWORK RULE
		Packages policy
			CREATE PACKAGES POLICY
			ALTER PACKAGES POLICY
			DROP PACKAGES POLICY
			SHOW PACKAGES POLICIES
			DESCRIBE PACKAGES POLICY
		Password policy
			CREATE PASSWORD POLICY
			ALTER PASSWORD POLICY
			DROP PASSWORD POLICY
			SHOW PASSWORD POLICIES
			DESCRIBE PASSWORD POLICY
		Session policy
			CREATE SESSION POLICY
			ALTER SESSION POLICY
			DROP SESSION POLICY
			SHOW SESSION POLICIES
			DESCRIBE SESSION POLICY
		Secret
			CREATE SECRET
			ALTER SECRET
			DROP SECRET
			SHOW SECRETS
			DESCRIBE SECRET
	Data Governance
		Column-level Security
			CREATE MASKING POLICY
			ALTER MASKING POLICY
			DROP MASKING POLICY
			SHOW MASKING POLICIES
			DESCRIBE MASKING POLICY
		Row access policy
			CREATE ROW ACCESS POLICY
			ALTER ROW ACCESS POLICY
			DROP ROW ACCESS POLICY
			SHOW ROW ACCESS POLICIES
			DESCRIBE ROW ACCESS POLICY
		Tag
			CREATE TAG
			ALTER TAG
			SHOW TAGS
			DROP TAG
			UNDROP TAG
	Privacy
		Aggregation policy
			CREATE AGGREGATION POLICY
			ALTER AGGREGATION POLICY
			DROP AGGREGATION POLICY
			SHOW AGGREGATION POLICIES
			DESCRIBE AGGREGATION POLICY
		Privacy policy
			CREATE PRIVACY POLICY
			ALTER PRIVACY POLICY
			DROP PRIVACY POLICY
			SHOW PRIVACY POLICIES
			DESCRIBE PRIVACY POLICY
		Projection policy
			CREATE PROJECTION POLICY
			ALTER PROJECTION POLICY
			DROP PROJECTION POLICY
			SHOW PROJECTION POLICIES
			DESCRIBE PROJECTION POLICY
	Data loading & unloading
		Stage
			CREATE STAGE
			ALTER STAGE
			DROP STAGE
			DESCRIBE STAGE
			SHOW STAGES
		File format
			ALTER FILE FORMAT
			CREATE FILE FORMAT
			DESCRIBE FILE FORMAT
			SHOW FILE FORMATS
			DROP FILE FORMAT
		External volume
			CREATE EXTERNAL VOLUME
			ALTER EXTERNAL VOLUME
			DROP EXTERNAL VOLUME
			UNDROP EXTERNAL VOLUME
			SHOW EXTERNAL VOLUMES
			DESCRIBE EXTERNAL VOLUME
		Pipe
			ALTER PIPE
			CREATE PIPE
			DESCRIBE PIPE
			SHOW PIPE
			DROP PIPE
		Snowpipe Streaming
			SHOW CHANNELS
		Loading and unloading
			COPY INTO <table>
			COPY INTO <location>
	File staging
		PUT
		COPY FILES
		GET
		LIST
		REMOVE
	Alerts
		CREATE ALERT
		ALTER ALERT
		DESCRIBE ALERT
		DROP ALERT
		SHOW ALERTS
		EXECUTE ALERT
	Native Apps Framework
		Application
			CREATE APPLICATION
			ALTER APPLICATION
			DESCRIBE APPLICATION
			DROP APPLICATION
			SHOW APPLICATIONS
		Application package
			CREATE APPLICATION PACKAGE
			ALTER APPLICATION PACKAGE
				ALTER APPLICATION PACKAGE ... RELEASE DIRECTIVE
				ALTER APPLICATION PACKAGE ... VERSION
			DROP APPLICATION PACKAGE
			SHOW APPLICATION PACKAGES
		Application role
			ALTER APPLICATION ROLE
			CREATE APPLICATION ROLE
			DROP APPLICATION ROLE
			GRANT APPLICATION ROLE
			REVOKE APPLICATION ROLE
			SHOW APPLICATION ROLES
		Additional commands
			CREATE VERSIONED SCHEMA
			SHOW PRIVILEGES
			SHOW REFERENCES
			SHOW RELEASE DIRECTIVES
			SHOW TELEMETRY EVENT DEFINITIONS
			SHOW VERSIONS
	Streamlit
		ALTER STREAMLIT
		CREATE STREAMLIT
		DESCRIBE STREAMLIT
		DROP STREAMLIT
		SHOW STREAMLITS
	Notebook
		CREATE NOTEBOOK
		EXECUTE NOTEBOOK
		ALTER NOTEBOOK
		SHOW NOTEBOOKS
		DESC NOTEBOOK
		DROP NOTEBOOK
	Snowpark Container Services
		Image registry and repository
			CREATE IMAGE REPOSITORY
			DROP IMAGE REPOSITORY
			SHOW IMAGE REPOSITORIES
			SHOW IMAGES IN IMAGE REPOSITORY
		Compute pool
			CREATE COMPUTE POOL
			ALTER COMPUTE POOL
			SHOW COMPUTE POOLS
			DESCRIBE COMPUTE POOL
			DROP COMPUTE POOL
		Service
			CREATE SERVICE
			ALTER SERVICE
			DROP SERVICE
			SHOW SERVICES
			DESCRIBE SERVICE
			SHOW ENDPOINTS
			SHOW SERVICE CONTAINERS IN SERVICE
			SHOW SERVICE INSTANCES IN SERVICE
		Job
			EXECUTE JOB SERVICE
		Service role
			GRANT SERVICE ROLE
			REVOKE SERVICE ROLE
			SHOW ROLES IN SERVICE
		Snapshot
			CREATE SNAPSHOT
			ALTER SNAPSHOT
			DESCRIBE SNAPSHOT
			SHOW SNAPSHOTS
			DROP SNAPSHOT
Function and stored procedure reference
	Summary of functions
	All functions (alphabetical)
		Aggregate
			General
				ANY_VALUE
				AVG
				CORR
				COUNT
				COUNT_IF
				COVAR_POP
				COVAR_SAMP
				LISTAGG
				MAX
				MAX_BY
				MEDIAN
				MIN
				MIN_BY
				MODE
				PERCENTILE_CONT
				PERCENTILE_DISC
				STDDEV, STDDEV_SAMP
				STDDEV_POP
				SUM
				VAR_POP
				VAR_SAMP
				VARIANCE
				VARIANCE_POP
				VARIANCE_SAMP
			Bitwise
				BITAND_AGG
				BITOR_AGG
				BITXOR_AGG
			Boolean
				BOOLAND_AGG
				BOOLOR_AGG
				BOOLXOR_AGG
			Hash
				HASH_AGG
			Semi-structured
				ARRAY_AGG
				OBJECT_AGG
			Linear regression
				REGR_AVGX
				REGR_AVGY
				REGR_COUNT
				REGR_INTERCEPT
				REGR_R2
				REGR_SLOPE
				REGR_SXX
				REGR_SXY
				REGR_SYY
			Statistics and probability
				KURTOSIS
				SKEW
			Count distinct values
				ARRAY_UNION_AGG
				ARRAY_UNIQUE_AGG
				BITMAP_BIT_POSITION
				BITMAP_BUCKET_NUMBER
				BITMAP_COUNT
				BITMAP_CONSTRUCT_AGG
				BITMAP_OR_AGG
			Cardinality estimation
				APPROX_COUNT_DISTINCT
				HLL
				HLL_ACCUMULATE
				HLL_COMBINE
				HLL_ESTIMATE
				HLL_EXPORT
				HLL_IMPORT
			Similarity estimation
				APPROXIMATE_JACCARD_INDEX
				APPROXIMATE_SIMILARITY
				MINHASH
				MINHASH_COMBINE
			Frequency estimation
				APPROX_TOP_K
				APPROX_TOP_K_ACCUMULATE
				APPROX_TOP_K_COMBINE
				APPROX_TOP_K_ESTIMATE
			Percentile estimation
				APPROX_PERCENTILE
				APPROX_PERCENTILE_ACCUMULATE
				APPROX_PERCENTILE_COMBINE
				APPROX_PERCENTILE_ESTIMATE
			Utilities
				GROUPING
				GROUPING_ID
		Bitwise expression
			BITAND
			BITAND_AGG
			BITNOT
			BITOR
			BITOR_AGG
			BITSHIFTLEFT
			BITSHIFTRIGHT
			BITXOR
			BITXOR_AGG
			GETBIT
		Conditional expression
			[NOT] BETWEEN
			BOOLAND
			BOOLNOT
			BOOLOR
			BOOLXOR
			CASE
			COALESCE
			DECODE
			EQUAL_NULL
			GREATEST
			GREATEST_IGNORE_NULLS
			IFF
			IFNULL
			[NOT] IN
			IS [NOT] DISTINCT FROM
			IS [NOT] NULL
			IS_NULL_VALUE
			LEAST
			LEAST_IGNORE_NULLS
			NULLIF
			NULLIFZERO
			NVL
			NVL2
			REGR_VALX
			REGR_VALY
			ZEROIFNULL
		Context
			General
				CURRENT_CLIENT
				CURRENT_DATE
				CURRENT_IP_ADDRESS
				CURRENT_REGION
				CURRENT_TIME
				CURRENT_TIMESTAMP
				CURRENT_VERSION
				GETDATE
				LOCALTIME
				LOCALTIMESTAMP
				SYSDATE
				SYSTIMESTAMP
			Session
				ALL_USER_NAMES
				CURRENT_ACCOUNT
				CURRENT_ACCOUNT_NAME
				CURRENT_ORGANIZATION_NAME
				CURRENT_ROLE
				CURRENT_AVAILABLE_ROLES
				CURRENT_SECONDARY_ROLES
				CURRENT_SESSION
				CURRENT_STATEMENT
				CURRENT_TRANSACTION
				CURRENT_USER
				GETVARIABLE
				LAST_QUERY_ID
				LAST_TRANSACTION
			Session object
				CURRENT_DATABASE
				CURRENT_ROLE_TYPE
				CURRENT_SCHEMA
				CURRENT_SCHEMAS
				CURRENT_WAREHOUSE
				INVOKER_ROLE
				INVOKER_SHARE
				IS_APPLICATION_ROLE_IN_SESSION
				IS_DATABASE_ROLE_IN_SESSION
				IS_GRANTED_TO_INVOKER_ROLE
				IS_INSTANCE_ROLE_IN_SESSION
				IS_ROLE_IN_SESSION
				POLICY_CONTEXT
			Alert
				GET_CONDITION_QUERY_UUID
		Conversion
			Any data type
				CAST, ::
				TRY_CAST
			Text, character, binary data types
				TO_CHAR
				TO_VARCHAR
				TO_BINARY
				TRY_TO_BINARY
			Numeric data types
				TO_DECIMAL
				TO_NUMBER
				TO_NUMERIC
				TO_DOUBLE
				TRY_TO_NUMBER
				TRY_TO_DECIMAL
				TRY_TO_NUMERIC
				TRY_TO_DOUBLE
			Boolean data types
				TO_BOOLEAN
				TRY_TO_BOOLEAN
			Date and time data types
				TO_DATE
				DATE
				TO_TIME
				TIME
				TO_TIMESTAMP
				TO_TIMESTAMP_LTZ
				TO_TIMESTAMP_NTZ
				TO_TIMESTAMP_TZ
				TRY_TO_DATE
				TRY_TO_TIME
				TRY_TO_TIMESTAMP
				TRY_TO_TIMESTAMP_LTZ
				TRY_TO_TIMESTAMP_NTZ
				TRY_TO_TIMESTAMP_TZ
			Semi-structured data types
				TO_ARRAY
				TO_OBJECT
				TO_VARIANT
			Geospatial data types
				TO_GEOGRAPHY
				TRY_TO_GEOGRAPHY
				ST_GEOGRAPHYFROMWWKB
				ST_GEOGRAPHYFROMWKT
				TO_GEOMETRY
				TRY_TO_GEOMETRY
				ST_GEOMETRYFROMWKB
				ST_GEOMETRYFROMWKT
			Data generation
				Random
					RANDOM
					RANDSTR
					UUID_STRING
				Controlled distribution
					NORMAL
					UNIFORM
					ZIPF
					SEQ1
					SEQ2
					SEQ4
					SEQ8
			Data metric
				Accuracy
					BLANK_COUNT
					BLANK_PERCENT
					NULL_COUNT
					NULL_PERCENT
				Freshness
					DATA_METRIC_SCHEDULED_TIME
					FRESHNESS
				Statistics
					AVG
					MIN
					MAX
					STDDEV
				Uniqueness
					DUPLICATE_COUNT
				Volume
					ROW_COUNT
					UNIQUE_COUNT
			Date & time
				Construction
					DATE_FROM_PARTS
					TIME_FROM_PARTS
					TIMESTAMP_FROM_PARTS
				Extraction
					DATE_PART
					DAYNAME
					EXTRACT
					HOUR
					MINUTE
					SECOND
					LAST_DAY
					MONTHNAME
					NEXT_DAY
					PREVIOUS_DAY
					YEAR
					YEAROFWEEK
					YEAROFWEEKISO
					DAY
					DAYOFMONTH
					DAYOFWEEK
					DAYOFWEEKISO
					DAYOFYEAR
					WEEK
					WEEKOFYEAR
					WEEKISO
					MONTH
					QUARTER
				Addition & subtraction
					ADD_MONTHS
					DATEADD
					DATEDIFF
					MONTHS_BETWEEN
					TIMEADD
					TIMEDIFF
					TIMESTAMPADD
					TIMESTAMPDIFF
				Truncation
					DATE_TRUNC
					TIME_SLICE
					TRUNC
				Conversion
					TO_DATE
					DATE
					TO_TIME
					TIME
					TO_TIMESTAMP
					TO_TIMESTAMP_LTZ
					TO_TIMESTAMP_NTZ
					TO_TIMESTAMP_TZ
					TRY_TO_DATE
					TRY_TO_TIME
					TRY_TO_TIMESTAMP
					TRY_TO_TIMESTAMP_LTZ
					TRY_TO_TIMESTAMP_NTZ
					TRY_TO_TIMESTAMP_TZ
				Time zone
					CONVERT_TIMEZONE
				Alerts
					LAST_SUCCESSFUL_SCHEDULED_TIME
					SCHEDULED_TIME
			Differential privacy
				DP_INTERVAL_HIGH
				DP_INTERVAL_LOW
				ESTIMATE_REMAINING_DP_AGGREGATES
			Encryption
				ENCRYPT
				DECRYPT
				TRY_DECRYPT
				ENCRYPT_RAW
				DECRYPT_RAW
				TRY_DECRYPT_RAW
			File
				GET_STAGE_LOCATION
				GET_RELATIVE_PATH
				GET_ABSOLUTE_PATH
				GET_PRESIGNED_URL
				BUILD_SCOPED_FILE_URL
				BUILD_STAGE_FILE_URL
			Geospatial
				Conversion, input, parsing
					ST_GEOGFROMGEOHASH
					ST_GEOGPOINTFROMGEOHASH
					ST_GEOGRAPHYFROMWKB
					ST_GEOGRAPHYFROMWKT
					ST_GEOMETRYFROMWKB
					ST_GEOMETRYFROMWKT
					ST_GEOMFROMGEOHASH
					ST_GEOMPOINTFROMGEOHASH
					TO_GEOGRAPHY
					TO_GEOMETRY
					TRY_TO_GEOGRAPHY
					TRY_TO_GEOMETRY
				Conversion, output, formatting
					ST_ASGEOJSON
					ST_ASWKB
					ST_ASBINARY
					ST_ASEWKB
					ST_ASWKT
					ST_ASTEXT
					ST_ASEWKT
					ST_GEOHASH
				Constructor
					ST_MAKELINE
					ST_MAKEGEOMPOINT
					ST_GEOMPOINT
					ST_MAKEPOINT
					ST_POINT
					ST_MAKEPOLYGON
					ST_POLYGON
					ST_MAKEPOLYGONORIENTED
				Accessor
					ST_DIMENSION
					ST_ENDPOINT
					ST_POINTN
					ST_SRID
					ST_STARTPOINT
					ST_X
					ST_XMAX
					ST_XMIN
					ST_Y
					ST_YMAX
					ST_YMIN
				Relationship and measurement
					HAVERSINE
					ST_AREA
					ST_AZIMUTH
					ST_CONTAINS
					ST_COVEREDBY
					ST_COVERS
					ST_DISJOINT
					ST_DISTANCE
					ST_DWITHIN
					ST_HAUSDORFFDISTANCE
					ST_INTERSECTS
					ST_LENGTH
					ST_NPOINTS
					ST_NUMPOINTS
					ST_PERIMETER
					ST_WITHIN
				Transformation
					ST_BUFFER
					ST_CENTROID
					ST_COLLECT
					ST_DIFFERENCE
					ST_ENVELOPE
					ST_INTERPOLATE
					ST_INTERSECTION
					ST_INTERSECTION_AGG
					ST_SETSRID
					ST_SIMPLIFY
					ST_SYMDIFFERENCE
					ST_TRANSFORM
					ST_UNION
					ST_UNION_AGG
				Utility
					ST_ISVALID
				H3
					H3_CELL_TO_BOUNDARY
					H3_CELL_TO_CHILDREN
					H3_CELL_TO_CHILDREN_STRING
					H3_CELL_TO_PARENT
					H3_CELL_TO_POINT
					H3_COMPACT_CELLS
					H3_COMPACT_CELLS_STRINGS
					H3_COVERAGE
					H3_COVERAGE_STRINGS
					H3_GET_RESOLUTION
					H3_GRID_DISK
					H3_GRID_DISTANCE
					H3_GRID_PATH
					H3_INT_TO_STRING
					H3_IS_PENTAGON
					H3_IS_VALID_CELL
					H3_LATLNG_TO_CELL
					H3_LATLNG_TO_CELL_STRING
					H3_POINT_TO_CELL
					H3_POINT_TO_CELL_STRING
					H3_POLYGON_TO_CELLS
					H3_POLYGON_TO_CELLS_STRINGS
					H3_STRING_TO_INT
					H3_TRY_COVERAGE
					H3_TRY_COVERAGE_STRINGS
					H3_TRY_GRID_DISTANCE
					H3_TRY_GRID_PATH
					H3_TRY_POLYGON_TO_CELLS
					H3_TRY_POLYGON_TO_CELLS_STRINGS
					H3_UNCOMPACT_CELLS
					H3_UNCOMPACT_CELLS_STRINGS
			Hash
				HASH
				HASH_AGG
			Metadata
				GENERATE_COLUMN_DESCRIPTION
				GET_DDL
			Notification
				Integration configuration
					EMAIL_INTEGRATION_CONFIG
					INTEGRATION
				Message construction
					APPLICATION_JSON
					TEXT_HTML
					TEXT_PLAIN
				Message sanitization
					SANITIZE_WEBHOOK_CONTENT
			Numeric
				Arithmetic
					DIV0
					DIV0NULL
				Rounding and truncation
					ABS
					CEIL
					FLOOR
					MOD
					ROUND
					SIGN
					TRUNCATE
					TRUNC
				Exponent and root
					CBRT
					EXP
					FACTORIAL
					POW
					POWER
					SQRT
					SQUARE
				Logarithmic
					LN
					LOG
				Trigonometric
					ACOS
					ACOSH
					ASIN
					ASINH
					ATAN
					ATAN2
					ATANH
					COS
					COSH
					COT
					DEGREES
					PI
					RADIANS
					SIN
					SINH
					TAN
					TANH
				Other
					WIDTH_BUCKET
			Regular expressions
				[ NOT ] REGEXP
				REGEXP_COUNT
				REGEXP_EXTRACT_ALL
				REGEXP_INSTR
				REGEXP_LIKE
				REGEXP_REPLACE
				REGEXP_SUBSTR
				REGEXP_SUBSTR_ALL
				[ NOT ] RLIKE
			Semi-structured and structured data
				JSON and XML parsing
					CHECK_JSON
					CHECK_XML
					JSON_EXTRACT_PATH_TEXT
					PARSE_JSON
					TRY_PARSE_JSON
					PARSE_XML
					STRIP_NULL_VALUE
				Array/object creation and manipulation
					ARRAY_AGG
					ARRAY_APPEND
					ARRAY_CAT
					ARRAY_COMPACT
					ARRAY_CONSTRUCT
					ARRAY_CONSTRUCT_COMPACT
					ARRAY_CONTAINS
					ARRAY_DISTINCT
					ARRAY_EXCEPT
					ARRAY_FLATTEN
					ARRAY_GENERATE_RANGE
					ARRAY_INSERT
					ARRAY_INTERSECTION
					ARRAY_MAX
					ARRAY_MIN
					ARRAY_POSITION
					ARRAY_PREPEND
					ARRAY_REMOVE
					ARRAY_REMOVE_AT
					ARRAY_REVERSE
					ARRAY_SIZE
					ARRAY_SLICE
					ARRAY_SORT
					ARRAY_TO_STRING
					ARRAY_UNION_AGG
					ARRAY_UNIQUE_AGG
					ARRAYS_OVERLAP
					ARRAYS_TO_OBJECT
					ARRAYS_ZIP
					OBJECT_AGG
					OBJECT_CONSTRUCT
					OBJECT_CONSTRUCT_KEEP_NULL
					OBJECT_DELETE
					OBJECT_INSERT
					OBJECT_PICK
				Higher-order
					FILTER
					REDUCE
					TRANSFORM
				Map creation and manipulation
					MAP_CAT
					MAP_CONTAINS_KEY
					MAP_DELETE
					MAP_INSERT
					MAP_KEYS
					MAP_PICK
					MAP_SIZE
				Extraction
					FLATTEN
					GET
					GET_IGNORE_CASE
					GET_PATH, :
					OBJECT_KEYS
					XMLGET
				Conversion/casting
					AS_<object_type>
					AS_ARRAY
					AS_BINARY
					AS_BOOLEAN
					AS_CHAR
					AS_VARCHAR
					AS_DATE
					AS_DECIMAL
					AS_NUMBER
					AS_DOUBLE
					AS_REAL
					AS_INTEGER
					AS_OBJECT
					AS_TIME
					AS_TIMESTAMP_LTZ
					AS_TIMESTAMP_NTZ
					AS_TIMESTAMP_TZ
					STRTOK_TO_ARRAY
					TO_ARRAY
					TO_JSON
					TO_OBJECT
					TO_VARIANT
					TO_XML
				Type predicates
					IS_<object_type>
					IS_ARRAY
					IS_BOOLEAN
					IS_BINARY
					IS_CHAR
					IS_VARCHAR
					IS_DATE
					IS_DATE_VALUE
					IS_DECIMAL
					IS_DOUBLE
					IS_REAL
					IS_INTEGER
					IS_NULL_VALUE
					IS_OBJECT
					IS_TIME
					IS_TIMESTAMP_LTZ
					IS_TIMESTAMP_NTZ
					IS_TIMESTAMP_TZ
					TYPEOF
			String & binary
				General manipulation
					ASCII
					BIT_LENGTH
					CHR
					CHAR
					CONCAT, ||
					CONCAT_WS
					INSERT
					LENGTH
					LEN
					LPAD
					LTRIM
					OCTET_LENGTH
					PARSE_IP
					PARSE_URL
					REPEAT
					REVERSE
					RPAD
					RTRIM
					RTRIMMED_LENGTH
					SOUNDEX
					SOUNDEX_P123
					SPACE
					SPLIT
					SPLIT_PART
					SPLIT_TO_TABLE
					STRTOK
					STRTOK_TO_ARRAY
					STRTOK_SPLIT_TO_TABLE
					TRANSLATE
					TRIM
					UNICODE
					UUID_STRING
				Full-text search
					SEARCH
					SEARCH_IP
				Case conversion
					INITCAP
					LOWER
					UPPER
				Regular expression matching
					[ NOT ] REGEXP
					REGEXP_COUNT
					REGEXP_EXTRACT_ALL
					REGEXP_INSTR
					REGEXP_LIKE
					REGEXP_REPLACE
					REGEXP_SUBSTR
					REGEXP_SUBSTR_ALL
					[ NOT ] RLIKE
				Other matching/comparison
					CHARINDEX
					CONTAINS
					EDITDISTANCE
					ENDSWITH
					[ NOT ] ILIKE
					ILIKE ANY
					JAROWINKLER_SIMILARITY
					LEFT
					[ NOT ] LIKE
					LIKE ALL
					LIKE ANY
					POSITION
					REPLACE
					RIGHT
					STARTSWITH
					SUBSTR
					SUBSTRING
				Compression/decompression
					COMPRESS
					DECOMPRESS_BINARY
					DECOMPRESS_STRING
				Encoding/decoding
					BASE64_DECODE_BINARY
					BASE64_DECODE_STRING
					BASE64_ENCODE
					HEX_DECODE_BINARY
					HEX_DECODE_STRING
					HEX_ENCODE
					TRY_BASE64_DECODE_BINARY
					TRY_BASE64_DECODE_STRING
					TRY_HEX_DECODE_BINARY
					TRY_HEX_DECODE_STRING
				Cryptographic/checksum
					MD5
					MD5_HEX
					MD5_BINARY
					MD5_NUMBER_LOWER64
					MD5_NUMBER_UPPER64
					SHA1
					SHA1_HEX
					SHA1_BINARY
					SHA2
					SHA2_HEX
					SHA2_BINARY
				Hash (non-cryptographic)
					HASH
					HASH_AGG
				Collation
					COLLATE
					COLLATION
				Large Language Model (LLM)
					CLASSIFY_TEXT
					COMPLETE
					EMBED_TEXT_768
					EMBED_TEXT_1024
					EXTRACT_ANSWER
				FINETUNE
					CREATE
					DESCRIBE
					SHOW
					CANCEL
				SENTIMENT
				SUMMARIZE
				PARSE_DOCUMENT
				TRANSLATE
			Helper functions for LLMs
				COUNT_TOKENS
				SEARCH_PREVIEW
				SPLIT_TEXT_RECURSIVE_CHARACTER
				TRY_COMPLETE
			System
				Control
					SYSTEM$ABORT_SESSION
					SYSTEM$ABORT_TRANSACTION
					SYSTEM$ADD_EVENT
					SYSTEM$AUTHORIZE_PRIVATELINK
					SYSTEM$AUTHORIZE_STAGE_PRIVATELINK_ACCESS
					SYSTEM$BLOCK_INTERNAL_STAGES_PUBLIC_ACCESS
					SYSTEM$CANCEL_ALL_QUERIES
					SYSTEM$CANCEL_QUERY
					SYSTEM$CLEANUP_DATABASE_ROLE_GRANTS
					SYSTEM$COMMIT_MOVE_ORGANIZATION_ACCOUNT
					SYSTEM$CONVERT_PIPES_SQS_TO_SNS
					SYSTEM$CREATE_BILLING_EVENT
					SYSTEM$CREATE_BILLING_EVENTS
					SYSTEM$DEPROVISION_PRIVATELINK_ENDPOINT
					SYSTEM$DISABLE_BEHAVIOR_CHANGE_BUNDLE
					SYSTEM$DISABLE_DATABASE_REPLICATION
					SYSTEM$DISABLE_PREVIEW_ACCESS
					SYSTEM$ENABLE_BEHAVIOR_CHANGE_BUNDLE
					SYSTEM$ENABLE_PREVIEW_ACCESS
					SYSTEM$GLOBAL_ACCOUNT_SET_PARAMETER
					SYSTEM$INITIATE_MOVE_ORGANIZATION_ACCOUNT
					SYSTEM$LINK_ACCOUNT_OBJECTS_BY_NAME
					SYSTEM$MIGRATE_SAML_IDP_REGISTRATION
					SYSTEM$PIPE_FORCE_RESUME
					SYSTEM$PIPE_REBINDING_WITH_NOTIFICATION_CHANNEL
					SYSTEM$PROVISION_PRIVATELINK_ENDPOINT
					SYSTEM$RESTORE_PRIVATELINK_ENDPOINT
					SYSTEM$REVOKE_PRIVATELINK
					SYSTEM$REVOKE_STAGE_PRIVATELINK_ACCESS
					SYSTEM$SEND_NOTIFICATIONS_TO_CATALOG
					SYSTEM$SET_APPLICATION_RESTRICTED_FEATURE_ACCESS
					SYSTEM$SET_EVENT_SHARING_ACCOUNT_FOR_REGION
					SYSTEM$SNOWPIPE_STREAMING_UPDATE_CHANNEL_OFFSET_TOKEN
					SYSTEM$TASK_DEPENDENTS_ENABLE
					SYSTEM$UNBLOCK_INTERNAL_STAGES_PUBLIC_ACCESS
					SYSTEM$UNSET_EVENT_SHARING_ACCOUNT_FOR_REGION
					SYSTEM$USER_TASK_CANCEL_ONGOING_EXECUTIONS
					SYSTEM$WAIT
				Information
					EXTRACT_SEMANTIC_CATEGORIES
					GET_ANACONDA_PACKAGES_REPODATA
					SHOW_PYTHON_PACKAGES_DEPENDENCIES
					SYSTEM$ALLOWLIST
					SYSTEM$ALLOWLIST_PRIVATELINK
					SYSTEM$AUTO_REFRESH_STATUS
					SYSTEM$BEHAVIOR_CHANGE_BUNDLE_STATUS
					SYSTEM$CLIENT_VERSION_INFO
					SYSTEM$CLUSTERING_DEPTH
					SYSTEM$CLUSTERING_INFORMATION
					SYSTEM$CLUSTERING_RATIO
					SYSTEM$CURRENT_USER_TASK_NAME
					SYSTEM$DATA_METRIC_SCAN
					SYSTEM$DATABASE_REFRESH_HISTORY
					SYSTEM$DATABASE_REFRESH_PROGRESS
					SYSTEM$DATABASE_REFRESH_PROGRESS_BY_JOB
					SYSTEM$ESTIMATE_AUTOMATIC_CLUSTERING_COSTS
					SYSTEM$ESTIMATE_SEARCH_OPTIMIZATION_COSTS
					SYSTEM$EXTERNAL_TABLE_PIPE_STATUS
					SYSTEM$FINISH_OAUTH_FLOW
					SYSTEM$GENERATE_SAML_CSR
					SYSTEM$GENERATE_SCIM_ACCESS_TOKEN
					SYSTEM$GET_AWS_SNS_IAM_POLICY
					SYSTEM$GET_CLASSIFICATION_RESULT
					SYSTEM$GET_CMK_AKV_CONSENT_URL
					SYSTEM$GET_CMK_CONFIG
					SYSTEM$GET_CMK_INFO
					SYSTEM$GET_CMK_KMS_KEY_POLICY
					SYSTEM$GET_COMPUTE_POOL_STATUS
					SYSTEM$GET_DIRECTORY_TABLE_STATUS
					SYSTEM$GET_GCP_KMS_CMK_GRANT_ACCESS_CMD
					SYSTEM$GET_ICEBERG_TABLE_INFORMATION
					SYSTEM$GET_LOGIN_FAILURE_DETAILS
					SYSTEM$GET_PREDECESSOR_RETURN_VALUE
					SYSTEM$GET_PREVIEW_ACCESS_STATUS
					SYSTEM$GET_PRIVATELINK
					SYSTEM$GET_PRIVATELINK_AUTHORIZED_ENDPOINTS
					SYSTEM$GET_PRIVATELINK_CONFIG
					SYSTEM$GET_PRIVATELINK_ENDPOINTS_INFO
					SYSTEM$GET_SERVICE_LOGS
					SYSTEM$GET_SERVICE_STATUS
					SYSTEM$GET_SNOWFLAKE_PLATFORM_INFO
					SYSTEM$GET_TAG
					SYSTEM$GET_TAG_ALLOWED_VALUES
					SYSTEM$GET_TAG_ON_CURRENT_COLUMN
					SYSTEM$GET_TAG_ON_CURRENT_TABLE
					SYSTEM$GET_TASK_GRAPH_CONFIG
					SYSTEM$INTERNAL_STAGES_PUBLIC_ACCESS_STATUS
					SYSTEM$IS_APPLICATION_INSTALLED_FROM_SAME_ACCOUNT
					SYSTEM$IS_APPLICATION_SHARING_EVENTS_WITH_PROVIDER
					SYSTEM$IS_LISTING_PURCHASED
					SYSTEM$IS_LISTING_TRIAL
					SYSTEM$LAST_CHANGE_COMMIT_TIME
					SYSTEM$LIST_APPLICATION_RESTRICTED_FEATURES
					SYSTEM$LIST_ICEBERG_TABLES_FROM_CATALOG
					SYSTEM$LIST_NAMESPACES_FROM_CATALOG
					SYSTEM$LOG
					SYSTEM$PIPE_STATUS
					SYSTEM$QUERY_REFERENCE
					SYSTEM$REFERENCE
					SYSTEM$REGISTER_CMK_INFO
					SYSTEM$REGISTRY_LIST_IMAGES
					SYSTEM$SET_RETURN_VALUE
					SYSTEM$SET_SPAN_ATTRIBUTES
					SYSTEM$SHOW_ACTIVE_BEHAVIOR_CHANGE_BUNDLES
					SYSTEM$SHOW_BUDGETS_IN_ACCOUNT
					SYSTEM$SHOW_EVENT_SHARING_ACCOUNTS
					SYSTEM$SHOW_MOVE_ORGANIZATION_ACCOUNT_STATUS
					SYSTEM$SHOW_OAUTH_CLIENT_SECRETS
					SYSTEM$START_OAUTH_FLOW
					SYSTEM$STREAM_BACKLOG
					SYSTEM$STREAM_GET_TABLE_TIMESTAMP
					SYSTEM$STREAM_HAS_DATA
					SYSTEM$TASK_RUNTIME_INFO
					SYSTEM$TYPEOF
					SYSTEM$VALIDATE_STORAGE_INTEGRATION
					SYSTEM$VERIFY_EXTERNAL_OAUTH_TOKEN
					SYSTEM$VERIFY_EXTERNAL_VOLUME
					SYSTEM$VERIFY_CMK_INFO
					SYSTEM$WHITELIST
					SYSTEM$WAIT_FOR_SERVICES
					SYSTEM$WHITELIST_PRIVATELINK
				Query information
					EXPLAIN_JSON
					GET_QUERY_OPERATOR_STATS
					SYSTEM$ESTIMATE_QUERY_ACCELERATION
					SYSTEM$EXPLAIN_PLAN_JSON
					SYSTEM$EXPLAIN_JSON_TO_TEXT
			Table
				Data loading
					INFER_SCHEMA
					VALIDATE
				Data generation
					GENERATOR
				Data conversion
					SPLIT_TO_TABLE
					STRTOK_SPLIT_TO_TABLE
				Differential privacy
					CUMULATIVE_PRIVACY_LOSSES
				ML-powered analysis
				Object modeling
					GET_OBJECT_REFERENCES
				Parameterized queries
					TO_QUERY
				Semi-structured queries
					FLATTEN
				Query results
					RESULT_SCAN
				Query profile
					GET_QUERY_OPERATOR_STATS
				User login
					LOGIN_HISTORY
					LOGIN_HISTORY_BY_USER
				Queries
					QUERY_HISTORY
					QUERY_HISTORY_BY_*
					QUERY_ACCELERATION_HISTORY
				Warehouse & storage usage
					DATABASE_STORAGE_USAGE_HISTORY
					WAREHOUSE_LOAD_HISTORY
					WAREHOUSE_METERING_HISTORY
					STAGE_STORAGE_USAGE_HISTORY
				Data Quality
					DATA_METRIC_FUNCTION_REFERENCES
					DATA_QUALITY_MONITORING_RESULTS
					SYSTEM$DATA_METRIC_SCAN
				Data Lineage
					GET_LINEAGE
				Network security
					NETWORK_RULE_REFERENCES
				Column & Row-level Security
					POLICY_REFERENCES
				Object tagging
					TAG_REFERENCES
					TAG_REFERENCES_ALL_COLUMNS
					TAG_REFERENCES_WITH_LINEAGE
				Account replication
					REPLICATION_GROUP_REFRESH_HISTORY
					REPLICATION_GROUP_REFRESH_PROGRESS
					REPLICATION_GROUP_REFRESH_PROCESS_BY_JOB
					REPLICATION_GROUP_USAGE_HISTORY
				Alerts
					ALERT_HISTORY
					SERVERLESS_ALERT_HISTORY
				Database replication
					DATABASE_REFRESH_HISTORY
					DATABASE_REFRESH_PROCESS
					DATABASE_REFRESH_PROGRESS_BY_JOB
					DATABASE_REPLICATION_USAGE_HISTORY
					REPLICATION_USAGE_HISTORY
				Data loading & transfer
					COPY_HISTORY
					DATA_TRANSFER_HISTORY
					PIPE_USAGE_HISTORY
					STAGE_DIRECTORY_FILE_REGISTRATION_HISTORY
					VALIDATE_PIPE_LOAD
				Data clustering (within tables)
					AUTOMATIC_CLUSTERING_HISTORY
				Dynamic tables
					DYNAMIC_TABLES
					DYNAMIC_TABLE_GRAPH_HISTORY
					DYNAMIC_TABLE_REFRESH_HISTORY
				External functions
					EXTERNAL_FUNCTIONS_HISTORY
				External tables
					AUTO_REFRESH_REGISTRATION_HISTORY
					EXTERNAL_TABLE_FILES
					EXTERNAL_TABLE_FILE_REGISTRATION_HISTORY
				Listing functions
					LISTING_REFRESH_HISTORY
					LISTING_REFRESH_PROGRESS
					Materialized views maintenance
					MATERIALIZED_VIEW_REFRESH_HISTORY
				Notifications
					NOTIFICATION_HISTORY
				SCIM maintenance
					REST_EVENT_HISTORY
				Search optimization maintenance
					SEARCH_OPTIMIZATION_HISTORY
				Streams
					SYSTEM$STREAM_BACKLOG
				Tasks
					COMPLETE_TASK_GRAPHS
					CURRENT_TASK_GRAPHS
					SERVERLESS_TASK_HISTORY
					TASK_DEPENDENTS
					TASK_HISTORY
			Vector
				Vector similiarity
					VECTOR_INNER_PRODUCT
					VECTOR_L2_DISTANCE
					VECTOR_COSINE_SIMILARITY
			Window
				Syntax and usage
				General
					ANY_VALUE
					AVG
					CONDITIONAL_CHANGE_EVENT
					CONDITIONAL_TRUE_EVENT
					CORR
					COUNT
					COUNT_IF
					COVAR_POP
					COVAR_SAMP
					LISTAGG
					MAX
					MEDIAN
					MIN
					MODE
					PERCENTILE_CONT
					PERCENTILE_DISC
					RATIO_TO_REPORT
					STDDEV, STDDEV_SAMP
					STDDEV_POP
					SUM
					VAR_POP
					VAR_SAMP
					VARIANCE
					VARIANCE_POP
					VARIANCE_SAMP
				Ranking
					CUME_DIST
					DENSE_RANK
					FIRST_VALUE
					LAG
					LAST_VALUE
					LEAD
					NTH_VALUE
					NTILE
					PERCENT_RANK
					RANK
					ROW_NUMBER
				Bitwise aggregation
					BITAND_AGG
					BITOR_AGG
					BITXOR_AGG
				Boolean aggregation
					BOOLAND_AGG
					BOOLOR_AGG
					BOOLXOR_AGG
				Hash aggregation
					HASH_AGG
				Semi-structured aggregation
					ARRAY_AGG
					OBJECT_AGG
				Counting distinct values
					ARRAY_UNION_AGG
					ARRAY_UNIQUE_AGG
					Linear regression
					REGR_AVGX
					REGR_AVGY
					REGR_COUNT
					REGR_INTERCEPT
					REGR_R2
					REGR_SLOPE
					REGR_SXX
					REGR_SXY
					REGR_SYY
				Statistics and probability
					KURTOSIS
				Cardinality estimation
					APPROX_COUNT_DISTINCT
					HLL
					HLL_ACCUMULATE
					HLL_COMBINE
					HLL_ESTIMATE
					HLL_EXPORT
					HLL_IMPORT
				Similarity estimation
					APPROXIMATE_JACCARD_INDEX
					APPROXIMATE_SIMILARITY
					MINHASH
					MINHASH_COMBINE
				Frequency estimation
					APPROX_TOP_K
					APPROX_TOP_K_ACCUMULATE
					APPROX_TOP_K_COMBINE
					APPROX_TOP_K_ESTIMATE
				Percentile estimation
					APPROX_PERCENTILE
					APPROX_PERCENTILE_ACCUMULATE
					APPROX_PERCENTILE_COMBINE
					APPROX_PERCENTILE_ESTIMATE
			Stored procedures
				Data classification
					ASSOCIATE_SEMANTIC_CATEGORY_TAGS
					SYSTEM$CLASSIFY
					SYSTEM$CLASSIFY_SCHEMA
					SYSTEM$CANCEL_CLASSIFY_SCHEMA
				Differential privacy
					RESET_PRIVACY_BUDGET
				Notifications
					SYSTEM$SEND_SNOWFLAKE_NOTIFICATION
					SYSTEM$SEND_EMAIL
				Data sharing and collaboration
					SYSTEM$REQUEST_LISTING_AND_WAIT
				Default event table
					ADD_ROW_ACCESS_POLICY_ON_EVENTS_VIEW
					DROP_ROW_ACCESS_POLICY_ON_EVENTS_VIEW
				Synthetic data
					GENERATE_SYNTHETIC_DATA
Class reference
	ANOMALY_DETECTION
		Commands
			CREATE ANOMALY_DETECTION
			DROP ANOMALY_DETECTION
			SHOW ANOMALY_DETECTION
		Methods
			DETECT_ANOMALIES
			EXPLAIN_FEATURE_IMPORTANCE
			SHOW_EVALUATION_METRICS
			SHOW_TRAINING_LOGS
	BUDGET
		Commands
			ALTER BUDGET
			CREATE BUDGET
			DROP BUDGET
			SHOW BUDGET
		Methods
			ACTIVATE
			ADD_NOTIFICATION_INTEGRATION
			ADD_RESOURCE
			DEACTIVATE
			GET_CONFIG
			GET_LINKED_RESOURCES
			GET_MEASUREMENT_TABLE
			GET_NOTIFICATION_EMAIL
			GET_NOTIFICATION_INTEGRATION_NAME
			GET_NOTIFICATION_INTEGRATIONS
			GET_NOTIFICATION_MUTE_FLAG
			GET_SERVICE_TYPE_USAGE
			GET_SPENDING_HISTORY
			GET_SPENDING_LIMIT
			REMOVE_NOTIFICATION_INTEGRATION
			REMOVE_RESOURCE
			SET_EMAIL_NOTIFICATIONS
			SET_NOTIFICATION_MUTE_FLAG
			SET_SPENDING_LIMIT
	CLASSIFICATION
		Commands
			ALTER CLASSIFICATION
			CREATE CLASSIFICATION
			DROP CLASSIFICATION
			SHOW CLASSIFICATION
		Methods
			PREDICT
			SHOW_CONFUSION_MATRIX
			SHOW_EVALUATION_METRICS
			SHOW_FEATURE_IMPORTANCE
			SHOW_GLOBAL_EVALUATION_METRICS
			SHOW_THRESHOLD_METRICS
			SHOW_TRAINING_LOGS
	CLASSIFICATION_PROFILE
		Commands
			CREATE CLASSIFICATION_PROFILE
			DROP CLASSIFICATION_PROFILE
			SHOW CLASSIFICATION_PROFILE
		Methods
			DESCRIBE
			SET_AUTO_TAG
			SET_CUSTOM_CLASSIFIERS
			SET_MAXIMUM_CLASSIFICATION_VALIDITY_DAYS
			SET_MINIMUM_OBJECT_AGE_FOR_CLASSIFICATION_DAYS
			SET_TAG_MAP
			UNSET_CUSTOM_CLASSIFIERS
			UNSET_MAXIMUM_CLASSIFICATION_VALIDITY_DAYS
			UNSET_TAG_MAP
	CUSTOM_CLASSIFIER
		Commands
			CREATE CUSTOM_CLASSIFIER
			DROP CUSTOM_CLASSIFIER
			SHOW CUSTOM_CLASSIFIERS
		Methods
			ADD_REGEX
			DELETE_CATEGORY
			LIST
	DOCUMENT_INTELLIGENCE
		Methods
			PREDICT
			FORECAST
		Commands
			CREATE FORECAST
			DROP FORECAST
			SHOW FORECAST
		Methods
			FORECAST
			EXPLAIN_FEATURE_IMPORTANCE
			SHOW_EVALUATION_METRICS
			SHOW_TRAINING_LOGS
	TOP_INSIGHTS
		Commands
			CREATE TOP_INSIGHTS
			DROP TOP_INSIGHTS
			SHOW TOP_INSIGHTS
		Methods
			GET_DRIVERS
Scripting reference
	BEGIN ... END
	BREAK
	CASE
	CLOSE
	CONTINUE
	DECLARE
	EXCEPTION
	FETCH
	FOR
	IF
	LET
	LOOP
	NULL
	OPEN
	RAISE
	REPEAT
	RETURN
	WHILE
General reference

	Parameters
	References
	Ternary logic
	Collation support
		Supported collation locales
	SQL format models
	object identifiers
		Requirements
		Literals and variables as identifiers
		Object name resolution
	Constraints
		Overview
		Creating
		Modifying
		Dropping
	SQL variables
	Bind variables
	Transactions
	Table literals
	SNOWFLAKE database
		Account Usage
			ACCESS_HISTORY
			AGGREGATE_ACCESS_HISTORY
			AGGREGATE_QUERY_HISTORY
			AGGREGATION_POLICIES
			ALERT_HISTORY
			AUTOMATIC_CLUSTERING_HISTORY
			BLOCK_STORAGE_HISTORY
			CLASS_INSTANCES
			CLASSES
			COLUMNS
			COMPLETE_TASK_GRAPHS
			COMPUTE_POOLS
			COPY_HISTORY
			CORTEX_FINE_TUNING_USAGE_HISTORY
			CORTEX_FUNCTIONS_USAGE_HISTORY
			CORTEX_SEARCH_SERVING_USAGE_HISTORY
			DATA_CLASSIFICATION_LATEST
			DATA_METRIC_FUNCTION_REFERENCES
			DATA_QUALITY_MONITORING_USAGE_HISTORY
			DATA_TRANSFER_HISTORY
			DATABASE_REPLICATION_USAGE_HISTORY
			DATABASE_STORAGE_USAGE_HISTORY
			DATABASES
			DOCUMENT_AI_USAGE_HISTORY
			DYNAMIC_TABLE_REFRESH_HISTORY
			ELEMENT_TYPES
			EVENT_USAGE_HISTORY
			EXTERNAL_ACCESS_HISTORY
			FIELDS
			FILE_FORMATS
			FUNCTIONS
			GRANTS_TO_ROLES
			GRANTS_TO_USERS
			HYBRID_TABLES
			HYBRID_TABLE_USAGE_HISTORY
			INDEX_COLUMNS
			INDEXES
			INTERNAL_DATA_TRANSFER_HISTORY
			LOAD_HISTORY
			LOCK_WAIT_HISTORY
			LOGIN_HISTORY
			MASKING_POLICIES
			MATERIALIZED_VIEW_REFRESH_HISTORY
			METERING_DAILY_HISTORY
			METERING_HISTORY
			NETWORK_POLICIES
			NETWORK_RULE_REFERENCES
			NETWORK_RULES
			OBJECT_DEPENDENCIES
			OUTBOUND_PRIVATELINK_ENDPOINTS
			PASSWORD_POLICIES
			PIPE_USAGE_HISTORY
			PIPES
			POLICY_REFERENCES
			PRIVACY_BUDGETS
			PRIVACY_POLICIES
			PROCEDURES
			PROJECTION_POLICIES
			QUERY_ACCELERATION_ELIGIBLE
			QUERY_ACCELERATION_HISTORY
			QUERY_ATTRIBUTION_HISTORY
			QUERY_HISTORY
			REFERENTIAL_CONSTRAINTS
			REPLICATION_GROUP_REFRESH_HISTORY
			REPLICATION_GROUP_USAGE_HISTORY
			REPLICATION_USAGE_HISTORY
			RESOURCE_MONITORS
			ROLES
			ROW_ACCESS_POLICIES
			SCHEMATA
			SEARCH_OPTIMIZATION_BENEFITS
			SEARCH_OPTIMIZATION_HISTORY
			SECRETS
			SEQUENCES
			SERVERLESS_ALERT_HISTORY
			SERVERLESS_TASK_HISTORY
			SERVICES
			SESSION_POLICIES
			SESSIONS
			SNOWPARK_CONTAINER_SERVICES_HISTORY
			SNOWPIPE_STREAMING_CLIENT_HISTORY
			SNOWPIPE_STREAMING_FILE_MIGRATION_HISTORY
			STAGE_STORAGE_USAGE_HISTORY
			STAGES
			STORAGE_USAGE
			TABLE_CONSTRAINTS
			TABLE_DML_HISTORY
			TABLE_PRUNING_HISTORY
			TABLE_STORAGE_METRICS
			TABLES
			TAG_REFERENCES
			TAGS
			TASK_HISTORY
			TASK_VERSIONS
			USERS
			VIEWS
			WAREHOUSE_EVENTS_HISTORY
			WAREHOUSE_LOAD_HISTORY
			WAREHOUSE_METERING_HISTORY
		Data Sharing Usage
			APPLICATION_STATE
			LISTING_ACCESS_HISTORY
			LISTING_AUTO_FULFILLMENT_DATABASE_STORAGE_DAILY
			LISTING_AUTO_FULFILLMENT_REFRESH_DAILY
			LISTING_CONSUMPTION_DAILY
			LISTING_EVENTS_DAILY
			LISTING_TELEMETRY_DAILY
			MARKETPLACE_DISBURSEMENT_REPORT
			MARKETPLACE_LISTING_INVOICE_STATUS
			MARKETPLACE_PAID_USAGE_DAILY
			MONETIZED_USAGE_DAILY
		Local
			DATA_QUALITY_MONITORING_RESULTS
		Monitoring
			ICEBERG_ACCESS_ERRORS
		Organization Usage
			ACCOUNTS
			AUTOMATIC_CLUSTERING_HISTORY
			CONTRACT_ITEMS
			DATA_TRANSFER_DAILY_HISTORY
			DATA_TRANSFER_HISTORY
			DATABASE_STORAGE_USAGE_HISTORY
			LISTING_AUTO_FULFILLMENT_USAGE_HISTORY
			MARKETPLACE_DISBURSEMENT_REPORT
			MARKETPLACE_PAID_USAGE_DAILY
			MATERIALIZED_VIEW_REFRESH_HISTORY
			METERING_DAILY_HISTORY
			MONETIZED_USAGE_DAILY
			PIPE_USAGE_HISTORY
			QUERY_ACCELERATION_HISTORY
			RATE_SHEET_DAILY
			REMAINING_BALANCE_DAILY
			REPLICATION_GROUP_USAGE_HISTORY
			REPLICATION_USAGE_HISTORY
			STAGE_STORAGE_USAGE_HISTORY
			SEARCH_OPTIMIZATION_HISTORY
			STORAGE_DAILY_HISTORY
			USAGE_IN_CURRENCY_DAILY
			WAREHOUSE_METERING_HISTORY
		Telemetry
			EVENTS_VIEW
		SNOWFLAKE database roles
		Snowflake classes
		Snowflake Information Schema
			APPLICABLE_ROLES
			CLASS_INSTANCE_FUNCTIONS
			CLASS_INSTANCE_PROCEDURES
			CLASS_INSTANCES
			CLASSES
			COLUMNS
			CORTEX_SEARCH_SERVICES
			CURRENT_PACKAGES_POLICY
			DATABASES
			ELEMENT_TYPES
			ENABLED_ROLES
			EVENT_TABLES
			EXTERNAL_TABLES
			FIELDS
			FILE_FORMATS
			FUNCTIONS
			HYBRID_TABLES
			INDEXES
			INDEX_COLUMNS
			INFORMATION_SCHEMA_CATALOG_NAME
			LOAD_HISTORY
			MODEL_VERSIONS
			OBJECT_PRIVILEGES
			PACKAGES
			PIPES
			PROCEDURES
			REFERENTIAL_CONSTRAINTS
			REPLICATION_DATABASES
			REPLICATION_GROUPS
			SCHEMATA
			SEQUENCES
			SERVICES
			STAGES
			TABLE_CONSTRAINTS
			TABLE_PRIVILEGES
			TABLE_STORAGE_METRICS
			TABLES
			USAGE_PRIVILEGES
			VIEWS
		Metadata fields
		Conventions
		Reserved keywords
API reference




Context functions
~~~~~~~~~~~~~~~~~~~~

Context functions -- General
~~~~~~~~~~~~~~~~~~~~

Even we can use IP address range for safety reasons

select CURRENT_IP_ADDRESS();

+----------------------+
| CURRENT_IP_ADDRESS() |
|----------------------|
| 223.185.22.219       |
+----------------------+

https://whatismyipaddress.com/ -- Visit and see current IP of the machine - IPv4: 223.185.22.219 -- Wow

select current_Date current_Date();  -- Both works in SQL but in scripting lang need to used with ()

select CURRENT_REGION();  -- Current region for the account where the current user is logged in. 
+------------------+
| CURRENT_REGION() |
|------------------|
| AWS_US_WEST_2    |
+------------------+

Show the current region when the current user is logged into an account in an organization that spans multiple region groups:

+----------------------+
| CURRENT_REGION()     |
|----------------------|
| PUBLIC.AWS_US_WEST_2 |
+----------------------+

CURRENT_TIME( [ <fract_sec_precision> ] ) -- fract_sec_precision 0-9 digits for seconds

select CURRENT_TIME(3), CURRENT_TIME(9);  -- not working 
+-----------------+-----------------+
| CURRENT_TIME(3) | CURRENT_TIME(9) |
|-----------------+-----------------|
| 22:07:54        | 22:07:54        |
+-----------------+-----------------+

Fractional seconds are only displayed if they have been explicitly set in the TIME_OUTPUT_FORMAT parameter for the session (e.g. 'HH24:MI:SS.FF').

alter session set TIME_OUTPUT_FORMAT='HH24:MI:SS.FF';

select CURRENT_TIME(3), CURRENT_TIME(9);  -- works now
+-----------------+--------------------+
| CURRENT_TIME(3) | CURRENT_TIME(9)    |
|-----------------+--------------------|
| 22:17:25.258    | 22:17:25.258000000 |
+-----------------+--------------------+

SELECT CURRENT_TIME;
SELECT LOCALTIME(); --- ANSI compliant alias for CURRENT_TIME

+--------------------+
| CURRENT_TIME       |
|--------------------|
| 22:18:54.373000000 |
+--------------------+

select CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(9);  
select CURRENT_TIMESTAMP(3), LOCALTIMESTAMP(9), ;     -- ANSI compliant alias for CURRENT_TIMESTAMP
SELECT CURRENT_TIMESTAMP(3), GETDATE();     -- alias for CURRENT_TIMESTAMP
select CURRENT_TIMESTAMP(3), SYSDATE();     -- alias for CURRENT_TIMESTAMP
select CURRENT_TIMESTAMP(3), SYSTIMESTAMP();     -- alias for CURRENT_TIMESTAMP

Fractional seconds are only displayed if they have been explicitly set in the TIMESTAMP_OUTPUT_FORMAT parameter for the session (e.g. 'YYYY-MM-DD HH24:MI:SS.FF').

Context functions -- Session
~~~~~~~~~~~~~~~~~~~~

Users with any active role can retrieve the list of all usernames in the current account.

select all_user_names();
+--------------------------------+
| ALL_USER_NAMES()               |
|--------------------------------|
| [ "NESANAWSNEW", "SNOWFLAKE" ] |
+--------------------------------+

Usernames (i.e. the NAME property value) are the unique identifier of the user object in Snowflake, while login names (i.e. the LOGIN_NAME property value) are used to authenticate to Snowflake. Usernames are not sensitive data and are returned by other commands and functions (e.g. SHOW GRANTS). Login names are sensitive data.

show grants;
+-------------------------------+--------------+------------+--------------+------------+
| created_on                    | role         | granted_to | grantee_name | granted_by |
|-------------------------------+--------------+------------+--------------+------------|
| 2024-11-18 08:39:12.483 -0800 | ACCOUNTADMIN | USER       | NESANAWSNEW  |            |
| 2024-11-18 08:39:16.477 -0800 | ORGADMIN     | USER       | NESANAWSNEW  |            |
+-------------------------------+--------------+------------+--------------+------------+
2 Row(s) produced. Time Elapsed: 0.325s

As a best practice, username and login name values should be different. To update existing username or login name values, execute the ALTER USER command. When creating new users with the CREATE USER command, ensure that the NAME and LOGIN_NAME values are different.

SELECT CURRENT_ACCOUNT();
+-------------------+
| CURRENT_ACCOUNT() |
|-------------------|
| CPB95846          |
+-------------------+

SELECT CURRENT_ACCOUNT_NAME();
+------------------------+
| CURRENT_ACCOUNT_NAME() |
|------------------------|
| JXB47930               |
+------------------------+

SELECT CURRENT_ORGANIZATION_NAME();
+-----------------------------+
| CURRENT_ORGANIZATION_NAME() |
|-----------------------------|
| CRCNDFT                     |
+-----------------------------+

SELECT CURRENT_ROLE();

Granting access on a secure UDF or secure view that contains this function to a share is allowed. When the secure UDF or secure view is accessed from the data sharing consumer account, this function always returns a NULL value.

Snowflake returns a NULL value if this function is used in a masking policy or row access policy that is assigned to a shared table or view.

CURRENT_AVAILABLE_ROLES, CURRENT_ROLE , CURRENT_SECONDARY_ROLES , IS_ROLE_IN_SESSION

This CURRENT_AVAILABLE_ROLES function returns a list of account-level roles only when queried by a user. Querying the function using a service that has no active user could result in a failed query. For example, the function does not return a list of roles when queried within a task, because the task runs are executed by a system service that is not associated with a user. In this case, the query could time out because the query plan cannot be completed.
This function does not return the names of database roles, application roles, or class instance roles.
This function does not account for role activation in a session.
For example, if specifying this function in the conditions of a masking policy or a row access policy, the policy might inadvertently restrict access.
If role activation and role hierarchy is necessary in the policy conditions, use IS_ROLE_IN_SESSION.

select CURRENT_AVAILABLE_ROLES();
+------------------------------------------------------------------------------------+
| CURRENT_AVAILABLE_ROLES()                                                          |
|------------------------------------------------------------------------------------|
| [ "ACCOUNTADMIN", "ORGADMIN", "PUBLIC", "SECURITYADMIN", "SYSADMIN", "USERADMIN" ] |
+------------------------------------------------------------------------------------+

select CURRENT_SECONDARY_ROLES();
+---------------------------+
| CURRENT_SECONDARY_ROLES() |
|---------------------------|
| {"roles":"","value":""}   |
+---------------------------+

SELECT INDEX,VALUE,THIS FROM TABLE(FLATTEN(input => PARSE_JSON(CURRENT_AVAILABLE_ROLES())));

+-------+-----------------+--------------------+
| INDEX | VALUE           | THIS               |
|-------+-----------------+--------------------|
|     0 | "ACCOUNTADMIN"  | [                  |
|       |                 |   "ACCOUNTADMIN",  |
|       |                 |   "ORGADMIN",      |
|       |                 |   "PUBLIC",        |
|       |                 |   "SECURITYADMIN", |
|       |                 |   "SYSADMIN",      |
|       |                 |   "USERADMIN"      |
|       |                 | ]                  |
|     1 | "ORGADMIN"      | [                  |
|       |                 |   "ACCOUNTADMIN",  |
|       |                 |   "ORGADMIN",      |
|       |                 |   "PUBLIC",        |
|       |                 |   "SECURITYADMIN", |
|       |                 |   "SYSADMIN",      |
|       |                 |   "USERADMIN"      |
|       |                 | ]                  |
|     2 | "PUBLIC"        | [                  |
|       |                 |   "ACCOUNTADMIN",  |
|       |                 |   "ORGADMIN",      |
|       |                 |   "PUBLIC",        |
|       |                 |   "SECURITYADMIN", |
|       |                 |   "SYSADMIN",      |
|       |                 |   "USERADMIN"      |
|       |                 | ]                  |
|     3 | "SECURITYADMIN" | [                  |
|       |                 |   "ACCOUNTADMIN",  |
|       |                 |   "ORGADMIN",      |
|       |                 |   "PUBLIC",        |
|       |                 |   "SECURITYADMIN", |
|       |                 |   "SYSADMIN",      |
|       |                 |   "USERADMIN"      |
|       |                 | ]                  |
|     4 | "SYSADMIN"      | [                  |
|       |                 |   "ACCOUNTADMIN",  |
|       |                 |   "ORGADMIN",      |
|       |                 |   "PUBLIC",        |
|       |                 |   "SECURITYADMIN", |
|       |                 |   "SYSADMIN",      |
|       |                 |   "USERADMIN"      |
|       |                 | ]                  |
|     5 | "USERADMIN"     | [                  |
|       |                 |   "ACCOUNTADMIN",  |
|       |                 |   "ORGADMIN",      |
|       |                 |   "PUBLIC",        |
|       |                 |   "SECURITYADMIN", |
|       |                 |   "SYSADMIN",      |
|       |                 |   "USERADMIN"      |
|       |                 | ]                  |
+-------+-----------------+--------------------+
6 Row(s) produced. Time Elapsed: 1157.569s

Returns a unique system identifier for the Snowflake session corresponding to the present connection. will generally be a system-generated alphanumeric string. It is NOT derived from the user name or user account.

SELECT CURRENT_SESSION();
+-------------------+
| CURRENT_SESSION() |
|-------------------|
| 748007209440346   |
+-------------------+

SELECT 2.71, CURRENT_STATEMENT();

CURRENT_TRANSACTION, LAST_TRANSACTION , DESCRIBE TRANSACTION

begin TRANSACTION;

SELECT CURRENT_TRANSACTION();
+-----------------------+
| CURRENT_TRANSACTION() |
|-----------------------|
| 1732436987323000000   |
+-----------------------+
1 Row(s) produced. Time Elapsed: 0.448s

rollback; -- must commit or rollback to end the transaction

SELECT CURRENT_TRANSACTION();
+-----------------------+
| CURRENT_TRANSACTION() |
|-----------------------|
| NULL                  |
+-----------------------+
1 Row(s) produced. Time Elapsed: 0.590s

SELECT LAST_TRANSACTION();    -- Same as above as the transaction ended.

+---------------------+
| LAST_TRANSACTION()  |
|---------------------|
| 1732436987323000000 |
+---------------------+

CURRENT_USER

SELECT CURRENT_USER();

+----------------+
| CURRENT_USER() |
|----------------|
| NESANAWSNEW    |
+----------------+

To comply with the ANSI standard, this function can be called without parentheses in SQL statements.

However, if you are setting a Snowflake Scripting variable to an expression that calls the function (for example, my_var := CURRENT_USER();), you must include the parentheses. For more information, see the usage notes for context functions.

Granting access on a secure UDF or secure view that contains this function to a share is allowed. When the secure UDF or secure view is accessed from the data sharing consumer account, this function always returns a NULL value.

Snowflake returns a NULL value if this function is used in a masking policy or row access policy that is assigned to a shared table or view.

GETVARIABLE

SET MY_LOCAL_VARIABLE= 'my_local_variable_value';

SELECT 
    GETVARIABLE('MY_LOCAL_VARIABLE'),      -- must be upper case
    SESSION_CONTEXT('MY_LOCAL_VARIABLE'),   -- must be upper case
    $my_local_variable;       -- Can be lower case
+----------------------------------+--------------------------------------+-------------------------+
| GETVARIABLE('MY_LOCAL_VARIABLE') | SESSION_CONTEXT('MY_LOCAL_VARIABLE') | $MY_LOCAL_VARIABLE      |
|----------------------------------+--------------------------------------+-------------------------|
| my_local_variable_value          | my_local_variable_value              | my_local_variable_value |
+----------------------------------+--------------------------------------+-------------------------+

When variables are created with the SET command, the variable names are forced to all upper case. The functions GETVARIABLE and SESSION_CONTEXT must pass the uppercase version of the function name. The “$” notation works with either uppercase or lowercase variable names.

SET var_2 = 'value_2';

SELECT 
    GETVARIABLE('var_2'),  -- Returns NULL 
    GETVARIABLE('VAR_2'),
    SESSION_CONTEXT('var_2'),  -- Returns NULL 
    SESSION_CONTEXT('VAR_2'),
    $var_2,
    $VAR_2;

+----------------------+----------------------+--------------------------+--------------------------+---------+---------+
| GETVARIABLE('VAR_2') | GETVARIABLE('VAR_2') | SESSION_CONTEXT('VAR_2') | SESSION_CONTEXT('VAR_2') | $VAR_2  | $VAR_2  |
|----------------------+----------------------+--------------------------+--------------------------+---------+---------|
| NULL                 | value_2              | NULL                     | value_2                  | value_2 | value_2 |
+----------------------+----------------------+--------------------------+--------------------------+---------+---------+

LAST_QUERY_ID

LAST_QUERY_ID( [ <num> ] )  -- [ <num> ] is Default: -1 Specifies the query to return, based on the position of the query (within the session).

LAST_QUERY_ID(1) returns the first query.

LAST_QUERY_ID(2) returns the second query.

LAST_QUERY_ID(6) returns the sixth query.

LAST_QUERY_ID(-1) returns the most recently-executed query (equivalent to LAST_QUERY_ID()).

LAST_QUERY_ID(-2) returns the second most recently-executed query.

SELECT LAST_QUERY_ID();
+--------------------------------------+
| LAST_QUERY_ID()                      |
|--------------------------------------|
| 01b894fc-0004-386c-0002-a84f00016536 |
+--------------------------------------+

SELECT LAST_QUERY_ID(1);
+--------------------------------------+
| LAST_QUERY_ID(1)                     |
|--------------------------------------|
| 01b89410-0004-3869-0002-a84f000195c2 |
+--------------------------------------+


RESULT_SCAN

RESULT_SCAN ( { '<query_id>' | <query_index>  | LAST_QUERY_ID() } )

SELECT $1 AS value FROM VALUES (1), (2), (3);
+-------+
| VALUE |
|-------|
|     1 |
|     2 |
|     3 |
+-------+
3 Row(s) produced. Time Elapsed: 0.340s

SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE value > 1;

+-------+
| VALUE |
|-------|
|     2 |
|     3 |
+-------+
2 Row(s) produced. Time Elapsed: 1.048s

SELECT * FROM table(RESULT_SCAN(LAST_QUERY_ID(-2)));
+-------+
| VALUE |
|-------|
|     1 |
|     2 |
|     3 |
+-------+

SELECT * FROM table(RESULT_SCAN(LAST_QUERY_ID(1)));
+----------------+----------------+
| CURRENT_USER() | CURRENT_ROLE() |
|----------------+----------------|
| NESANAWSNEW    | ACCOUNTADMIN   |
+----------------+----------------+

Examples using DESCRIBE and SHOW commands

DESC USER NESANAWSNEW;  -- display all the user property 

SELECT "property", "value" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
  WHERE "property" = 'DEFAULT_ROLE'
  ;

+--------------+--------------+
| property     | value        |
|--------------+--------------|
| DEFAULT_ROLE | ACCOUNTADMIN |
+--------------+--------------+

show tables limit 2; --- limit can be used with show commands Also

SHOW TABLES;
-- Show the tables that are more than 2 days old and that are empty
-- (i.e. tables that I might have forgotten about).
SELECT "database_name", "schema_name", "name" as "table_name", "rows", "created_on"
    FROM table(RESULT_SCAN(LAST_QUERY_ID()))
    WHERE "rows" = 0 AND "created_on" < DATEADD(day, -2, CURRENT_TIMESTAMP())
    ORDER BY "created_on";

Process the result of a SHOW TABLES command to extract the tables in descending order of size. This example also illustrates using a UDF to show table size in a slightly more human-readable format.

-- Show byte counts with suffixes such as "KB", "MB", and "GB".
CREATE OR REPLACE FUNCTION NiceBytes(NUMBER_OF_BYTES INTEGER)
RETURNS VARCHAR
AS
$$
CASE
    WHEN NUMBER_OF_BYTES < 1024
        THEN NUMBER_OF_BYTES::VARCHAR
    WHEN NUMBER_OF_BYTES >= 1024 AND NUMBER_OF_BYTES < 1048576
        THEN (NUMBER_OF_BYTES / 1024)::VARCHAR || 'KB'
   WHEN NUMBER_OF_BYTES >= 1048576 AND NUMBER_OF_BYTES < (POW(2, 30))
       THEN (NUMBER_OF_BYTES / 1048576)::VARCHAR || 'MB'
    ELSE
        (NUMBER_OF_BYTES / POW(2, 30))::VARCHAR || 'GB'
END
$$
;
SHOW TABLES;
-- Show all of my tables in descending order of size.
SELECT "database_name", "schema_name", "name" as "table_name", NiceBytes("bytes") AS "size"
    FROM table(RESULT_SCAN(LAST_QUERY_ID()))
    ORDER BY "bytes" DESC;

+---------------+-------------+------------+--------------+
| database_name | schema_name | table_name | size         |
|---------------+-------------+------------+--------------|
| LEARNING_SQL  | PUBLIC      | CUSTOMER   | 4.539551MB   |
| LEARNING_SQL  | PUBLIC      | LINEITEM   | 3.652344MB   |
| LEARNING_SQL  | PUBLIC      | ORDERS     | 3.611816MB   |
| LEARNING_SQL  | PUBLIC      | PARTSUPP   | 727.000000KB |
| LEARNING_SQL  | PUBLIC      | SUPPLIER   | 489.000000KB |
| LEARNING_SQL  | PUBLIC      | PART       | 144.500000KB |
| LEARNING_SQL  | PUBLIC      | PERSON     | 4.000000KB   |
| LEARNING_SQL  | PUBLIC      | NATION     | 3.000000KB   |
| LEARNING_SQL  | PUBLIC      | EMPLOYEE   | 2.000000KB   |
| LEARNING_SQL  | PUBLIC      | REGION     | 2.000000KB   |
| LEARNING_SQL  | PUBLIC      | DEPARTMENT | 1.500000KB   |
| LEARNING_SQL  | PUBLIC      | EMPL_DEPT  | 1.000000KB   |
+---------------+-------------+------------+--------------+

Examples using a stored procedure

Stored procedure calls return a value. However, this value cannot be processed directly because you cannot embed a stored procedure call in another statement. To work around this limitation, you can use RESULT_SCAN to process the value returned by a stored procedure. A simplified example is below:

First, create a procedure that returns a “complicated” value (in this case, a string that contains JSON-compatible data) that can be processed after it has been returned from the CALL.

CREATE OR REPLACE PROCEDURE return_JSON()
    RETURNS VARCHAR
    LANGUAGE JavaScript
    AS
    $$
        return '{"keyA": "ValueA", "keyB": "ValueB"}';
    $$
    ;
	
CALL return_JSON();
+--------------------------------------+
| RETURN_JSON                          |
|--------------------------------------|
| {"keyA": "ValueA", "keyB": "ValueB"} |
+--------------------------------------+

SELECT $1 AS output_col FROM table(RESULT_SCAN(LAST_QUERY_ID()));  -- Get the first (and only) column:
+--------------------------------------+
| OUTPUT_COL                           |
|--------------------------------------|
| {"keyA": "ValueA", "keyB": "ValueB"} |
+--------------------------------------+

SELECT PARSE_JSON(output_col) AS JSON_COL FROM table(RESULT_SCAN(LAST_QUERY_ID())); -- Convert from a VARCHAR to a VARIANT:
+---------------------+
| JSON_COL            |
|---------------------|
| {                   |
|   "keyA": "ValueA", |
|   "keyB": "ValueB"  |
| }                   |
+---------------------+

SELECT JSON_COL:keyB FROM table(RESULT_SCAN(LAST_QUERY_ID()));  -- Extract the value that corresponds to the key “keyB”:
+---------------+
| JSON_COL:KEYB |
|---------------|
| "ValueB"      |
+---------------+

Achive all the above in single query

CALL return_JSON();
+--------------------------------------+
| RETURN_JSON                          |
|--------------------------------------|
| {"keyA": "ValueA", "keyB": "ValueB"} |
+--------------------------------------+
SELECT JSON_COL:keyB 
   FROM (
        SELECT PARSE_JSON($1::VARIANT) AS JSON_COL 
            FROM table(RESULT_SCAN(LAST_QUERY_ID()))
        );
+---------------+
| JSON_COL:KEYB |
|---------------|
| "ValueB"      |
+---------------+

Same using the column name of the returned value of proc

CALL return_JSON();
+--------------------------------------+
| RETURN_JSON                          |
|--------------------------------------|
| {"keyA": "ValueA", "keyB": "ValueB"} |
+--------------------------------------+
SELECT JSON_COL:keyB
        FROM (
             SELECT PARSE_JSON(RETURN_JSON::VARIANT) AS JSON_COL 
                 FROM table(RESULT_SCAN(LAST_QUERY_ID()))
             );
+---------------+
| JSON_COL:KEYB |
|---------------|
| "ValueB"      |
+---------------+


Context functions -- Session Objects
~~~~~~~~~~~~~~~~~~~~











































